# Generated by Django 4.1 on 2022-08-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=200)),
                ('times', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=200)),
                ('times', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
