# Generated by Django 4.1 on 2022-08-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parkingrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonUpload',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Rates',
        ),
    ]
